// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/api/k8shelld.proto

package k8shelldpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode for Unix socket operation
type UnixSocketMode int32

const (
	UnixSocketMode_UNIX_SOCKET_MODE_LISTEN UnixSocketMode = 0
	UnixSocketMode_UNIX_SOCKET_MODE_DIAL   UnixSocketMode = 1
)

// Enum value maps for UnixSocketMode.
var (
	UnixSocketMode_name = map[int32]string{
		0: "UNIX_SOCKET_MODE_LISTEN",
		1: "UNIX_SOCKET_MODE_DIAL",
	}
	UnixSocketMode_value = map[string]int32{
		"UNIX_SOCKET_MODE_LISTEN": 0,
		"UNIX_SOCKET_MODE_DIAL":   1,
	}
)

func (x UnixSocketMode) Enum() *UnixSocketMode {
	p := new(UnixSocketMode)
	*p = x
	return p
}

func (x UnixSocketMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnixSocketMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_k8shelld_proto_enumTypes[0].Descriptor()
}

func (UnixSocketMode) Type() protoreflect.EnumType {
	return &file_pkg_api_k8shelld_proto_enumTypes[0]
}

func (x UnixSocketMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnixSocketMode.Descriptor instead.
func (UnixSocketMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{0}
}

// Which log to return
type LogType int32

const (
	LogType_LOG_TYPE_APP     LogType = 0 // runtime app log
	LogType_LOG_TYPE_INSTALL LogType = 1 // install log
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_TYPE_APP",
		1: "LOG_TYPE_INSTALL",
	}
	LogType_value = map[string]int32{
		"LOG_TYPE_APP":     0,
		"LOG_TYPE_INSTALL": 1,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_k8shelld_proto_enumTypes[1].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_pkg_api_k8shelld_proto_enumTypes[1]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{1}
}

// SystemInfo messages
type SystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoRequest) Reset() {
	*x = SystemInfoRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRequest) ProtoMessage() {}

func (x *SystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{0}
}

// SystemInfoResponse message
type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	System        *SystemMetrics         `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Mounts        []*MountUsage          `protobuf:"bytes,3,rep,name=mounts,proto3" json:"mounts,omitempty"`
	Docker        *DockerUsage           `protobuf:"bytes,4,opt,name=docker,proto3" json:"docker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfoResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SystemInfoResponse) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *SystemInfoResponse) GetMounts() []*MountUsage {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *SystemInfoResponse) GetDocker() *DockerUsage {
	if x != nil {
		return x.Docker
	}
	return nil
}

// SystemMetrics message
type SystemMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Uptime             string                 `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	CpuUsageMillicores float64                `protobuf:"fixed64,2,opt,name=cpuUsageMillicores,proto3" json:"cpuUsageMillicores,omitempty"`
	CpuLimitMillicores float64                `protobuf:"fixed64,3,opt,name=cpuLimitMillicores,proto3" json:"cpuLimitMillicores,omitempty"`
	MemoryUsageMiB     float64                `protobuf:"fixed64,4,opt,name=memoryUsageMiB,proto3" json:"memoryUsageMiB,omitempty"`
	MemLimitMiB        float64                `protobuf:"fixed64,5,opt,name=memLimitMiB,proto3" json:"memLimitMiB,omitempty"`
	CpuAvg1Min         float64                `protobuf:"fixed64,6,opt,name=cpuAvg1Min,proto3" json:"cpuAvg1Min,omitempty"`
	CpuAvg5Min         float64                `protobuf:"fixed64,7,opt,name=cpuAvg5Min,proto3" json:"cpuAvg5Min,omitempty"`
	CpuAvg15Min        float64                `protobuf:"fixed64,8,opt,name=cpuAvg15Min,proto3" json:"cpuAvg15Min,omitempty"`
	Users              uint32                 `protobuf:"varint,9,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{2}
}

func (x *SystemMetrics) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *SystemMetrics) GetCpuUsageMillicores() float64 {
	if x != nil {
		return x.CpuUsageMillicores
	}
	return 0
}

func (x *SystemMetrics) GetCpuLimitMillicores() float64 {
	if x != nil {
		return x.CpuLimitMillicores
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsageMiB() float64 {
	if x != nil {
		return x.MemoryUsageMiB
	}
	return 0
}

func (x *SystemMetrics) GetMemLimitMiB() float64 {
	if x != nil {
		return x.MemLimitMiB
	}
	return 0
}

func (x *SystemMetrics) GetCpuAvg1Min() float64 {
	if x != nil {
		return x.CpuAvg1Min
	}
	return 0
}

func (x *SystemMetrics) GetCpuAvg5Min() float64 {
	if x != nil {
		return x.CpuAvg5Min
	}
	return 0
}

func (x *SystemMetrics) GetCpuAvg15Min() float64 {
	if x != nil {
		return x.CpuAvg15Min
	}
	return 0
}

func (x *SystemMetrics) GetUsers() uint32 {
	if x != nil {
		return x.Users
	}
	return 0
}

// MountUsage message
type MountUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MountPoint     string                 `protobuf:"bytes,1,opt,name=mountPoint,proto3" json:"mountPoint,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	FsType         string                 `protobuf:"bytes,3,opt,name=fsType,proto3" json:"fsType,omitempty"`
	Options        []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	ReadOnly       bool                   `protobuf:"varint,5,opt,name=readOnly,proto3" json:"readOnly,omitempty"`
	IsLikelyTemp   bool                   `protobuf:"varint,6,opt,name=isLikelyTemp,proto3" json:"isLikelyTemp,omitempty"`
	TotalBytes     uint64                 `protobuf:"varint,10,opt,name=totalBytes,proto3" json:"totalBytes,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,11,opt,name=usedBytes,proto3" json:"usedBytes,omitempty"`
	FreeBytes      uint64                 `protobuf:"varint,12,opt,name=freeBytes,proto3" json:"freeBytes,omitempty"`
	AvailableBytes uint64                 `protobuf:"varint,13,opt,name=availableBytes,proto3" json:"availableBytes,omitempty"`
	TotalInodes    uint64                 `protobuf:"varint,14,opt,name=totalInodes,proto3" json:"totalInodes,omitempty"`
	FreeInodes     uint64                 `protobuf:"varint,15,opt,name=freeInodes,proto3" json:"freeInodes,omitempty"`
	DeclaredSize   uint64                 `protobuf:"varint,20,opt,name=declaredSize,proto3" json:"declaredSize,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MountUsage) Reset() {
	*x = MountUsage{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountUsage) ProtoMessage() {}

func (x *MountUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountUsage.ProtoReflect.Descriptor instead.
func (*MountUsage) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{3}
}

func (x *MountUsage) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *MountUsage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MountUsage) GetFsType() string {
	if x != nil {
		return x.FsType
	}
	return ""
}

func (x *MountUsage) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MountUsage) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *MountUsage) GetIsLikelyTemp() bool {
	if x != nil {
		return x.IsLikelyTemp
	}
	return false
}

func (x *MountUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *MountUsage) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *MountUsage) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *MountUsage) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *MountUsage) GetTotalInodes() uint64 {
	if x != nil {
		return x.TotalInodes
	}
	return 0
}

func (x *MountUsage) GetFreeInodes() uint64 {
	if x != nil {
		return x.FreeInodes
	}
	return 0
}

func (x *MountUsage) GetDeclaredSize() uint64 {
	if x != nil {
		return x.DeclaredSize
	}
	return 0
}

// DockerUsage message
type DockerUsage struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SocketPath            string                 `protobuf:"bytes,1,opt,name=socketPath,proto3" json:"socketPath,omitempty"`
	ApiVersion            string                 `protobuf:"bytes,2,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	DockerRootDir         string                 `protobuf:"bytes,3,opt,name=dockerRootDir,proto3" json:"dockerRootDir,omitempty"`
	ImagesBytes           uint64                 `protobuf:"varint,10,opt,name=imagesBytes,proto3" json:"imagesBytes,omitempty"`
	ContainersBytes       uint64                 `protobuf:"varint,11,opt,name=containersBytes,proto3" json:"containersBytes,omitempty"`
	ContainersRootFsBytes uint64                 `protobuf:"varint,12,opt,name=containersRootFsBytes,proto3" json:"containersRootFsBytes,omitempty"`
	VolumesBytes          uint64                 `protobuf:"varint,13,opt,name=volumesBytes,proto3" json:"volumesBytes,omitempty"`
	BuildCacheBytes       uint64                 `protobuf:"varint,14,opt,name=buildCacheBytes,proto3" json:"buildCacheBytes,omitempty"`
	TotalBytes            uint64                 `protobuf:"varint,15,opt,name=totalBytes,proto3" json:"totalBytes,omitempty"`
	DeclaredSize          uint64                 `protobuf:"varint,20,opt,name=declaredSize,proto3" json:"declaredSize,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DockerUsage) Reset() {
	*x = DockerUsage{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerUsage) ProtoMessage() {}

func (x *DockerUsage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerUsage.ProtoReflect.Descriptor instead.
func (*DockerUsage) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{4}
}

func (x *DockerUsage) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *DockerUsage) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *DockerUsage) GetDockerRootDir() string {
	if x != nil {
		return x.DockerRootDir
	}
	return ""
}

func (x *DockerUsage) GetImagesBytes() uint64 {
	if x != nil {
		return x.ImagesBytes
	}
	return 0
}

func (x *DockerUsage) GetContainersBytes() uint64 {
	if x != nil {
		return x.ContainersBytes
	}
	return 0
}

func (x *DockerUsage) GetContainersRootFsBytes() uint64 {
	if x != nil {
		return x.ContainersRootFsBytes
	}
	return 0
}

func (x *DockerUsage) GetVolumesBytes() uint64 {
	if x != nil {
		return x.VolumesBytes
	}
	return 0
}

func (x *DockerUsage) GetBuildCacheBytes() uint64 {
	if x != nil {
		return x.BuildCacheBytes
	}
	return 0
}

func (x *DockerUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DockerUsage) GetDeclaredSize() uint64 {
	if x != nil {
		return x.DeclaredSize
	}
	return 0
}

// HandshakeRequest message
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	UserToken     string                 `protobuf:"bytes,2,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{5}
}

func (x *HandshakeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *HandshakeRequest) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

// HandshakeResponse message
type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{6}
}

func (x *HandshakeResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ShellRequest message
type ShellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ShellRequest_StartRequest
	//	*ShellRequest_Data
	Request       isShellRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{7}
}

func (x *ShellRequest) GetRequest() isShellRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ShellRequest) GetStartRequest() *ShellStartRequest {
	if x != nil {
		if x, ok := x.Request.(*ShellRequest_StartRequest); ok {
			return x.StartRequest
		}
	}
	return nil
}

func (x *ShellRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*ShellRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isShellRequest_Request interface {
	isShellRequest_Request()
}

type ShellRequest_StartRequest struct {
	StartRequest *ShellStartRequest `protobuf:"bytes,1,opt,name=start_request,json=startRequest,proto3,oneof"` // Start shell request
}

type ShellRequest_Data struct {
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"` // Data to send to the shell
}

func (*ShellRequest_StartRequest) isShellRequest_Request() {}

func (*ShellRequest_Data) isShellRequest_Request() {}

// ShellRequest message
type ShellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ShellResponse_StartResponse
	//	*ShellResponse_Data
	//	*ShellResponse_Terminate
	Response      isShellResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellResponse) Reset() {
	*x = ShellResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResponse) ProtoMessage() {}

func (x *ShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResponse.ProtoReflect.Descriptor instead.
func (*ShellResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{8}
}

func (x *ShellResponse) GetResponse() isShellResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ShellResponse) GetStartResponse() *ShellStartResponse {
	if x != nil {
		if x, ok := x.Response.(*ShellResponse_StartResponse); ok {
			return x.StartResponse
		}
	}
	return nil
}

func (x *ShellResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Response.(*ShellResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ShellResponse) GetTerminate() bool {
	if x != nil {
		if x, ok := x.Response.(*ShellResponse_Terminate); ok {
			return x.Terminate
		}
	}
	return false
}

type isShellResponse_Response interface {
	isShellResponse_Response()
}

type ShellResponse_StartResponse struct {
	StartResponse *ShellStartResponse `protobuf:"bytes,1,opt,name=start_response,json=startResponse,proto3,oneof"` // Start shell response
}

type ShellResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Data received from the shell
}

type ShellResponse_Terminate struct {
	Terminate bool `protobuf:"varint,3,opt,name=terminate,proto3,oneof"` // Terminate the shell session
}

func (*ShellResponse_StartResponse) isShellResponse_Response() {}

func (*ShellResponse_Data) isShellResponse_Response() {}

func (*ShellResponse_Terminate) isShellResponse_Response() {}

// ShellStartRequest message
type ShellStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdShell      string                 `protobuf:"bytes,1,opt,name=cmdShell,proto3" json:"cmdShell,omitempty"`     // Command to run the shell
	SetEnvVars    []string               `protobuf:"bytes,2,rep,name=setEnvVars,proto3" json:"setEnvVars,omitempty"` // Environment variables to be set in the the shell
	UsePty        bool                   `protobuf:"varint,3,opt,name=usePty,proto3" json:"usePty,omitempty"`        // True to use a pseudo-terminal
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`          // Terminal width
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`        // Terminal height
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`             // User to run the shell as, empty for default user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellStartRequest) Reset() {
	*x = ShellStartRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStartRequest) ProtoMessage() {}

func (x *ShellStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStartRequest.ProtoReflect.Descriptor instead.
func (*ShellStartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{9}
}

func (x *ShellStartRequest) GetCmdShell() string {
	if x != nil {
		return x.CmdShell
	}
	return ""
}

func (x *ShellStartRequest) GetSetEnvVars() []string {
	if x != nil {
		return x.SetEnvVars
	}
	return nil
}

func (x *ShellStartRequest) GetUsePty() bool {
	if x != nil {
		return x.UsePty
	}
	return false
}

func (x *ShellStartRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ShellStartRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ShellStartRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// ShellStartResponse message
type ShellStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pty           string                 `protobuf:"bytes,1,opt,name=pty,proto3" json:"pty,omitempty"` // PTY name if a pseudo-terminal is used, empty otherwise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellStartResponse) Reset() {
	*x = ShellStartResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStartResponse) ProtoMessage() {}

func (x *ShellStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStartResponse.ProtoReflect.Descriptor instead.
func (*ShellStartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{10}
}

func (x *ShellStartResponse) GetPty() string {
	if x != nil {
		return x.Pty
	}
	return ""
}

// ResizeTerminalRequest message
type ResizeTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`   // Terminal width
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"` // Terminal height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTerminalRequest) Reset() {
	*x = ResizeTerminalRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTerminalRequest) ProtoMessage() {}

func (x *ResizeTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTerminalRequest.ProtoReflect.Descriptor instead.
func (*ResizeTerminalRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{11}
}

func (x *ResizeTerminalRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResizeTerminalRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// ResizeTerminalResponse message
type ResizeTerminalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTerminalResponse) Reset() {
	*x = ResizeTerminalResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTerminalResponse) ProtoMessage() {}

func (x *ResizeTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTerminalResponse.ProtoReflect.Descriptor instead.
func (*ResizeTerminalResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{12}
}

// Request for the PortForward operation
type PortForwardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*PortForwardRequest_Destination
	//	*PortForwardRequest_Data
	Request       isPortForwardRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardRequest) Reset() {
	*x = PortForwardRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardRequest) ProtoMessage() {}

func (x *PortForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardRequest.ProtoReflect.Descriptor instead.
func (*PortForwardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{13}
}

func (x *PortForwardRequest) GetRequest() isPortForwardRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PortForwardRequest) GetDestination() *Destination {
	if x != nil {
		if x, ok := x.Request.(*PortForwardRequest_Destination); ok {
			return x.Destination
		}
	}
	return nil
}

func (x *PortForwardRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*PortForwardRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPortForwardRequest_Request interface {
	isPortForwardRequest_Request()
}

type PortForwardRequest_Destination struct {
	Destination *Destination `protobuf:"bytes,1,opt,name=destination,proto3,oneof"` // Destination details
}

type PortForwardRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Data to send to the destination
}

func (*PortForwardRequest_Destination) isPortForwardRequest_Request() {}

func (*PortForwardRequest_Data) isPortForwardRequest_Request() {}

// Destination details message
type Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // Destination IP address
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // Destination port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{14}
}

func (x *Destination) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Destination) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Response for the PortForward operation
type PortForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Data received from the destination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardResponse) Reset() {
	*x = PortForwardResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardResponse) ProtoMessage() {}

func (x *PortForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardResponse.ProtoReflect.Descriptor instead.
func (*PortForwardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{15}
}

func (x *PortForwardResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request for the Exec operation
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ExecRequest_CommandDetails
	//	*ExecRequest_Input
	//	*ExecRequest_Signal
	Request       isExecRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{16}
}

func (x *ExecRequest) GetRequest() isExecRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecRequest) GetCommandDetails() *CommandDetails {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_CommandDetails); ok {
			return x.CommandDetails
		}
	}
	return nil
}

func (x *ExecRequest) GetInput() []byte {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ExecRequest) GetSignal() string {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_Signal); ok {
			return x.Signal
		}
	}
	return ""
}

type isExecRequest_Request interface {
	isExecRequest_Request()
}

type ExecRequest_CommandDetails struct {
	CommandDetails *CommandDetails `protobuf:"bytes,1,opt,name=command_details,json=commandDetails,proto3,oneof"` // Command details including command and shell binary
}

type ExecRequest_Input struct {
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3,oneof"` // Input to send to the command
}

type ExecRequest_Signal struct {
	Signal string `protobuf:"bytes,3,opt,name=signal,proto3,oneof"` // Signal to send to the command
}

func (*ExecRequest_CommandDetails) isExecRequest_Request() {}

func (*ExecRequest_Input) isExecRequest_Request() {}

func (*ExecRequest_Signal) isExecRequest_Request() {}

// Response for the Exec operation
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	//	*ExecResponse_ExitCode
	Response      isExecResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{17}
}

func (x *ExecResponse) GetResponse() isExecResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecResponse_Response interface {
	isExecResponse_Response()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"` // Standard output
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"` // Standard error
}

type ExecResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"` // Exit code when the process exits
}

func (*ExecResponse_Stdout) isExecResponse_Response() {}

func (*ExecResponse_Stderr) isExecResponse_Response() {}

func (*ExecResponse_ExitCode) isExecResponse_Response() {}

// Command details message
type CommandDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                            // Initial command with arguments
	ShellBinary   string                 `protobuf:"bytes,2,opt,name=shell_binary,json=shellBinary,proto3" json:"shell_binary,omitempty"` // Optional shell binary to use (e.g., "/bin/sh"), empty for none
	EnvVars       []string               `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`             // Environment variables to be set for the command
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                  // User to run the executable as, empty for default user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDetails) Reset() {
	*x = CommandDetails{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDetails) ProtoMessage() {}

func (x *CommandDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDetails.ProtoReflect.Descriptor instead.
func (*CommandDetails) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{18}
}

func (x *CommandDetails) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandDetails) GetShellBinary() string {
	if x != nil {
		return x.ShellBinary
	}
	return ""
}

func (x *CommandDetails) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CommandDetails) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// Request for the UnixSocket operation
type UnixSocketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*UnixSocketRequest_StartRequest
	//	*UnixSocketRequest_Data
	Request       isUnixSocketRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixSocketRequest) Reset() {
	*x = UnixSocketRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketRequest) ProtoMessage() {}

func (x *UnixSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocketRequest.ProtoReflect.Descriptor instead.
func (*UnixSocketRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{19}
}

func (x *UnixSocketRequest) GetRequest() isUnixSocketRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *UnixSocketRequest) GetStartRequest() *UnixSocketStartRequest {
	if x != nil {
		if x, ok := x.Request.(*UnixSocketRequest_StartRequest); ok {
			return x.StartRequest
		}
	}
	return nil
}

func (x *UnixSocketRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*UnixSocketRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUnixSocketRequest_Request interface {
	isUnixSocketRequest_Request()
}

type UnixSocketRequest_StartRequest struct {
	StartRequest *UnixSocketStartRequest `protobuf:"bytes,1,opt,name=start_request,json=startRequest,proto3,oneof"` // Start Unix socket request
}

type UnixSocketRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Data to send to the Unix socket
}

func (*UnixSocketRequest_StartRequest) isUnixSocketRequest_Request() {}

func (*UnixSocketRequest_Data) isUnixSocketRequest_Request() {}

// Response for the UnixSocket operation
type UnixSocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Data to send to the Unix socket
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixSocketResponse) Reset() {
	*x = UnixSocketResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketResponse) ProtoMessage() {}

func (x *UnixSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocketResponse.ProtoReflect.Descriptor instead.
func (*UnixSocketResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{20}
}

func (x *UnixSocketResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UnixSocketStartRequest message
type UnixSocketStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          UnixSocketMode         `protobuf:"varint,1,opt,name=mode,proto3,enum=k8shelld.UnixSocketMode" json:"mode,omitempty"`
	SocketPath    string                 `protobuf:"bytes,2,opt,name=socketPath,proto3" json:"socketPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixSocketStartRequest) Reset() {
	*x = UnixSocketStartRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketStartRequest) ProtoMessage() {}

func (x *UnixSocketStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocketStartRequest.ProtoReflect.Descriptor instead.
func (*UnixSocketStartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{21}
}

func (x *UnixSocketStartRequest) GetMode() UnixSocketMode {
	if x != nil {
		return x.Mode
	}
	return UnixSocketMode_UNIX_SOCKET_MODE_LISTEN
}

func (x *UnixSocketStartRequest) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

type CommandMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CommandMessage_Command
	//	*CommandMessage_Reply
	Payload       isCommandMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandMessage) Reset() {
	*x = CommandMessage{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandMessage) ProtoMessage() {}

func (x *CommandMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandMessage.ProtoReflect.Descriptor instead.
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{22}
}

func (x *CommandMessage) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandMessage) GetPayload() isCommandMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandMessage) GetCommand() string {
	if x != nil {
		if x, ok := x.Payload.(*CommandMessage_Command); ok {
			return x.Command
		}
	}
	return ""
}

func (x *CommandMessage) GetReply() string {
	if x != nil {
		if x, ok := x.Payload.(*CommandMessage_Reply); ok {
			return x.Reply
		}
	}
	return ""
}

type isCommandMessage_Payload interface {
	isCommandMessage_Payload()
}

type CommandMessage_Command struct {
	Command string `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type CommandMessage_Reply struct {
	Reply string `protobuf:"bytes,3,opt,name=reply,proto3,oneof"`
}

func (*CommandMessage_Command) isCommandMessage_Payload() {}

func (*CommandMessage_Reply) isCommandMessage_Payload() {}

type ListAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{23}
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*AppStatus           `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{24}
}

func (x *ListAppsResponse) GetApps() []*AppStatus {
	if x != nil {
		return x.Apps
	}
	return nil
}

type AppStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Age           string                 `protobuf:"bytes,6,opt,name=age,proto3" json:"age,omitempty"`
	Restarts      int32                  `protobuf:"varint,7,opt,name=restarts,proto3" json:"restarts,omitempty"`
	Protocol      string                 `protobuf:"bytes,8,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppStatus) Reset() {
	*x = AppStatus{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatus) ProtoMessage() {}

func (x *AppStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatus.ProtoReflect.Descriptor instead.
func (*AppStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{25}
}

func (x *AppStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AppStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AppStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AppStatus) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *AppStatus) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *AppStatus) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type InstallAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppRequest) Reset() {
	*x = InstallAppRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppRequest) ProtoMessage() {}

func (x *InstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppRequest.ProtoReflect.Descriptor instead.
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{26}
}

func (x *InstallAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstallAppRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type InstallAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppResponse) Reset() {
	*x = InstallAppResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppResponse) ProtoMessage() {}

func (x *InstallAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppResponse.ProtoReflect.Descriptor instead.
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{27}
}

type StartAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAppRequest) Reset() {
	*x = StartAppRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAppRequest) ProtoMessage() {}

func (x *StartAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAppRequest.ProtoReflect.Descriptor instead.
func (*StartAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{28}
}

func (x *StartAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAppResponse) Reset() {
	*x = StartAppResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAppResponse) ProtoMessage() {}

func (x *StartAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAppResponse.ProtoReflect.Descriptor instead.
func (*StartAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{29}
}

type StopAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAppRequest) Reset() {
	*x = StopAppRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAppRequest) ProtoMessage() {}

func (x *StopAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAppRequest.ProtoReflect.Descriptor instead.
func (*StopAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{30}
}

func (x *StopAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAppResponse) Reset() {
	*x = StopAppResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAppResponse) ProtoMessage() {}

func (x *StopAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAppResponse.ProtoReflect.Descriptor instead.
func (*StopAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{31}
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          LogType                `protobuf:"varint,2,opt,name=type,proto3,enum=k8shelld.LogType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{32}
}

func (x *GetLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLogsRequest) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_LOG_TYPE_APP
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{33}
}

func (x *GetLogsResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type GetLogsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          LogType                `protobuf:"varint,2,opt,name=type,proto3,enum=k8shelld.LogType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsStreamRequest) Reset() {
	*x = GetLogsStreamRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsStreamRequest) ProtoMessage() {}

func (x *GetLogsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsStreamRequest.ProtoReflect.Descriptor instead.
func (*GetLogsStreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{34}
}

func (x *GetLogsStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLogsStreamRequest) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_LOG_TYPE_APP
}

type GetLogsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsStreamResponse) Reset() {
	*x = GetLogsStreamResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsStreamResponse) ProtoMessage() {}

func (x *GetLogsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsStreamResponse.ProtoReflect.Descriptor instead.
func (*GetLogsStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{35}
}

func (x *GetLogsStreamResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_pkg_api_k8shelld_proto protoreflect.FileDescriptor

const file_pkg_api_k8shelld_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/api/k8shelld.proto\x12\bk8shelld\"\x13\n" +
	"\x11SystemInfoRequest\"\xb6\x01\n" +
	"\x12SystemInfoResponse\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12/\n" +
	"\x06system\x18\x02 \x01(\v2\x17.k8shelld.SystemMetricsR\x06system\x12,\n" +
	"\x06mounts\x18\x03 \x03(\v2\x14.k8shelld.MountUsageR\x06mounts\x12-\n" +
	"\x06docker\x18\x04 \x01(\v2\x15.k8shelld.DockerUsageR\x06docker\"\xc9\x02\n" +
	"\rSystemMetrics\x12\x16\n" +
	"\x06uptime\x18\x01 \x01(\tR\x06uptime\x12.\n" +
	"\x12cpuUsageMillicores\x18\x02 \x01(\x01R\x12cpuUsageMillicores\x12.\n" +
	"\x12cpuLimitMillicores\x18\x03 \x01(\x01R\x12cpuLimitMillicores\x12&\n" +
	"\x0ememoryUsageMiB\x18\x04 \x01(\x01R\x0ememoryUsageMiB\x12 \n" +
	"\vmemLimitMiB\x18\x05 \x01(\x01R\vmemLimitMiB\x12\x1e\n" +
	"\n" +
	"cpuAvg1Min\x18\x06 \x01(\x01R\n" +
	"cpuAvg1Min\x12\x1e\n" +
	"\n" +
	"cpuAvg5Min\x18\a \x01(\x01R\n" +
	"cpuAvg5Min\x12 \n" +
	"\vcpuAvg15Min\x18\b \x01(\x01R\vcpuAvg15Min\x12\x14\n" +
	"\x05users\x18\t \x01(\rR\x05users\"\xa0\x03\n" +
	"\n" +
	"MountUsage\x12\x1e\n" +
	"\n" +
	"mountPoint\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06fsType\x18\x03 \x01(\tR\x06fsType\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12\x1a\n" +
	"\breadOnly\x18\x05 \x01(\bR\breadOnly\x12\"\n" +
	"\fisLikelyTemp\x18\x06 \x01(\bR\fisLikelyTemp\x12\x1e\n" +
	"\n" +
	"totalBytes\x18\n" +
	" \x01(\x04R\n" +
	"totalBytes\x12\x1c\n" +
	"\tusedBytes\x18\v \x01(\x04R\tusedBytes\x12\x1c\n" +
	"\tfreeBytes\x18\f \x01(\x04R\tfreeBytes\x12&\n" +
	"\x0eavailableBytes\x18\r \x01(\x04R\x0eavailableBytes\x12 \n" +
	"\vtotalInodes\x18\x0e \x01(\x04R\vtotalInodes\x12\x1e\n" +
	"\n" +
	"freeInodes\x18\x0f \x01(\x04R\n" +
	"freeInodes\x12\"\n" +
	"\fdeclaredSize\x18\x14 \x01(\x04R\fdeclaredSize\"\x87\x03\n" +
	"\vDockerUsage\x12\x1e\n" +
	"\n" +
	"socketPath\x18\x01 \x01(\tR\n" +
	"socketPath\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x02 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rdockerRootDir\x18\x03 \x01(\tR\rdockerRootDir\x12 \n" +
	"\vimagesBytes\x18\n" +
	" \x01(\x04R\vimagesBytes\x12(\n" +
	"\x0fcontainersBytes\x18\v \x01(\x04R\x0fcontainersBytes\x124\n" +
	"\x15containersRootFsBytes\x18\f \x01(\x04R\x15containersRootFsBytes\x12\"\n" +
	"\fvolumesBytes\x18\r \x01(\x04R\fvolumesBytes\x12(\n" +
	"\x0fbuildCacheBytes\x18\x0e \x01(\x04R\x0fbuildCacheBytes\x12\x1e\n" +
	"\n" +
	"totalBytes\x18\x0f \x01(\x04R\n" +
	"totalBytes\x12\"\n" +
	"\fdeclaredSize\x18\x14 \x01(\x04R\fdeclaredSize\"X\n" +
	"\x10HandshakeRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12\x1d\n" +
	"\n" +
	"user_token\x18\x02 \x01(\tR\tuserToken\"p\n" +
	"\x11HandshakeResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"s\n" +
	"\fShellRequest\x12B\n" +
	"\rstart_request\x18\x01 \x01(\v2\x1b.k8shelld.ShellStartRequestH\x00R\fstartRequest\x12\x14\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04dataB\t\n" +
	"\arequest\"\x98\x01\n" +
	"\rShellResponse\x12E\n" +
	"\x0estart_response\x18\x01 \x01(\v2\x1c.k8shelld.ShellStartResponseH\x00R\rstartResponse\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12\x1e\n" +
	"\tterminate\x18\x03 \x01(\bH\x00R\tterminateB\n" +
	"\n" +
	"\bresponse\"\xa9\x01\n" +
	"\x11ShellStartRequest\x12\x1a\n" +
	"\bcmdShell\x18\x01 \x01(\tR\bcmdShell\x12\x1e\n" +
	"\n" +
	"setEnvVars\x18\x02 \x03(\tR\n" +
	"setEnvVars\x12\x16\n" +
	"\x06usePty\x18\x03 \x01(\bR\x06usePty\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\"&\n" +
	"\x12ShellStartResponse\x12\x10\n" +
	"\x03pty\x18\x01 \x01(\tR\x03pty\"E\n" +
	"\x15ResizeTerminalRequest\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\"\x18\n" +
	"\x16ResizeTerminalResponse\"p\n" +
	"\x12PortForwardRequest\x129\n" +
	"\vdestination\x18\x01 \x01(\v2\x15.k8shelld.DestinationH\x00R\vdestination\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\arequest\"1\n" +
	"\vDestination\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\")\n" +
	"\x13PortForwardResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x8f\x01\n" +
	"\vExecRequest\x12C\n" +
	"\x0fcommand_details\x18\x01 \x01(\v2\x18.k8shelld.CommandDetailsH\x00R\x0ecommandDetails\x12\x16\n" +
	"\x05input\x18\x02 \x01(\fH\x00R\x05input\x12\x18\n" +
	"\x06signal\x18\x03 \x01(\tH\x00R\x06signalB\t\n" +
	"\arequest\"m\n" +
	"\fExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\n" +
	"\n" +
	"\bresponse\"|\n" +
	"\x0eCommandDetails\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12!\n" +
	"\fshell_binary\x18\x02 \x01(\tR\vshellBinary\x12\x19\n" +
	"\benv_vars\x18\x03 \x03(\tR\aenvVars\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"}\n" +
	"\x11UnixSocketRequest\x12G\n" +
	"\rstart_request\x18\x01 \x01(\v2 .k8shelld.UnixSocketStartRequestH\x00R\fstartRequest\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\arequest\"(\n" +
	"\x12UnixSocketResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"f\n" +
	"\x16UnixSocketStartRequest\x12,\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x18.k8shelld.UnixSocketModeR\x04mode\x12\x1e\n" +
	"\n" +
	"socketPath\x18\x02 \x01(\tR\n" +
	"socketPath\"n\n" +
	"\x0eCommandMessage\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1a\n" +
	"\acommand\x18\x02 \x01(\tH\x00R\acommand\x12\x16\n" +
	"\x05reply\x18\x03 \x01(\tH\x00R\x05replyB\t\n" +
	"\apayload\"\x11\n" +
	"\x0fListAppsRequest\";\n" +
	"\x10ListAppsResponse\x12'\n" +
	"\x04apps\x18\x01 \x03(\v2\x13.k8shelld.AppStatusR\x04apps\"\xc1\x01\n" +
	"\tAppStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03age\x18\x06 \x01(\tR\x03age\x12\x1a\n" +
	"\brestarts\x18\a \x01(\x05R\brestarts\x12\x1a\n" +
	"\bprotocol\x18\b \x01(\tR\bprotocol\"=\n" +
	"\x11InstallAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x14\n" +
	"\x12InstallAppResponse\"%\n" +
	"\x0fStartAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x12\n" +
	"\x10StartAppResponse\"$\n" +
	"\x0eStopAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x11\n" +
	"\x0fStopAppResponse\"K\n" +
	"\x0eGetLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.k8shelld.LogTypeR\x04type\"#\n" +
	"\x0fGetLogsResponse\x12\x10\n" +
	"\x03log\x18\x01 \x01(\tR\x03log\"Q\n" +
	"\x14GetLogsStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.k8shelld.LogTypeR\x04type\"+\n" +
	"\x15GetLogsStreamResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line*H\n" +
	"\x0eUnixSocketMode\x12\x1b\n" +
	"\x17UNIX_SOCKET_MODE_LISTEN\x10\x00\x12\x19\n" +
	"\x15UNIX_SOCKET_MODE_DIAL\x10\x01*1\n" +
	"\aLogType\x12\x10\n" +
	"\fLOG_TYPE_APP\x10\x00\x12\x14\n" +
	"\x10LOG_TYPE_INSTALL\x10\x012\x9e\x01\n" +
	"\rSystemService\x12D\n" +
	"\tHandshake\x12\x1a.k8shelld.HandshakeRequest\x1a\x1b.k8shelld.HandshakeResponse\x12G\n" +
	"\n" +
	"SystemInfo\x12\x1b.k8shelld.SystemInfoRequest\x1a\x1c.k8shelld.SystemInfoResponse2\xa1\x01\n" +
	"\fShellService\x12<\n" +
	"\x05Shell\x12\x16.k8shelld.ShellRequest\x1a\x17.k8shelld.ShellResponse(\x010\x01\x12S\n" +
	"\x0eResizeTerminal\x12\x1f.k8shelld.ResizeTerminalRequest\x1a .k8shelld.ResizeTerminalResponse2d\n" +
	"\x12PortForwardService\x12N\n" +
	"\vPortForward\x12\x1c.k8shelld.PortForwardRequest\x1a\x1d.k8shelld.PortForwardResponse(\x010\x012H\n" +
	"\vExecService\x129\n" +
	"\x04Exec\x12\x15.k8shelld.ExecRequest\x1a\x16.k8shelld.ExecResponse(\x010\x012`\n" +
	"\x11UnixSocketService\x12K\n" +
	"\n" +
	"UnixSocket\x12\x1b.k8shelld.UnixSocketRequest\x1a\x1c.k8shelld.UnixSocketResponse(\x010\x012[\n" +
	"\x0eCommandService\x12I\n" +
	"\x0fCommandListener\x12\x18.k8shelld.CommandMessage\x1a\x18.k8shelld.CommandMessage(\x010\x012\xaf\x03\n" +
	"\n" +
	"AppService\x12A\n" +
	"\bListApps\x12\x19.k8shelld.ListAppsRequest\x1a\x1a.k8shelld.ListAppsResponse\x12G\n" +
	"\n" +
	"InstallApp\x12\x1b.k8shelld.InstallAppRequest\x1a\x1c.k8shelld.InstallAppResponse\x12A\n" +
	"\bStartApp\x12\x19.k8shelld.StartAppRequest\x1a\x1a.k8shelld.StartAppResponse\x12>\n" +
	"\aStopApp\x12\x18.k8shelld.StopAppRequest\x1a\x19.k8shelld.StopAppResponse\x12>\n" +
	"\aGetLogs\x12\x18.k8shelld.GetLogsRequest\x1a\x19.k8shelld.GetLogsResponse\x12R\n" +
	"\rGetLogsStream\x12\x1e.k8shelld.GetLogsStreamRequest\x1a\x1f.k8shelld.GetLogsStreamResponse0\x01B>Z<github.com/k8shell-io/k8shelld/pkg/api/k8shelldpb;k8shelldpbb\x06proto3"

var (
	file_pkg_api_k8shelld_proto_rawDescOnce sync.Once
	file_pkg_api_k8shelld_proto_rawDescData []byte
)

func file_pkg_api_k8shelld_proto_rawDescGZIP() []byte {
	file_pkg_api_k8shelld_proto_rawDescOnce.Do(func() {
		file_pkg_api_k8shelld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_k8shelld_proto_rawDesc), len(file_pkg_api_k8shelld_proto_rawDesc)))
	})
	return file_pkg_api_k8shelld_proto_rawDescData
}

var file_pkg_api_k8shelld_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_api_k8shelld_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_pkg_api_k8shelld_proto_goTypes = []any{
	(UnixSocketMode)(0),            // 0: k8shelld.UnixSocketMode
	(LogType)(0),                   // 1: k8shelld.LogType
	(*SystemInfoRequest)(nil),      // 2: k8shelld.SystemInfoRequest
	(*SystemInfoResponse)(nil),     // 3: k8shelld.SystemInfoResponse
	(*SystemMetrics)(nil),          // 4: k8shelld.SystemMetrics
	(*MountUsage)(nil),             // 5: k8shelld.MountUsage
	(*DockerUsage)(nil),            // 6: k8shelld.DockerUsage
	(*HandshakeRequest)(nil),       // 7: k8shelld.HandshakeRequest
	(*HandshakeResponse)(nil),      // 8: k8shelld.HandshakeResponse
	(*ShellRequest)(nil),           // 9: k8shelld.ShellRequest
	(*ShellResponse)(nil),          // 10: k8shelld.ShellResponse
	(*ShellStartRequest)(nil),      // 11: k8shelld.ShellStartRequest
	(*ShellStartResponse)(nil),     // 12: k8shelld.ShellStartResponse
	(*ResizeTerminalRequest)(nil),  // 13: k8shelld.ResizeTerminalRequest
	(*ResizeTerminalResponse)(nil), // 14: k8shelld.ResizeTerminalResponse
	(*PortForwardRequest)(nil),     // 15: k8shelld.PortForwardRequest
	(*Destination)(nil),            // 16: k8shelld.Destination
	(*PortForwardResponse)(nil),    // 17: k8shelld.PortForwardResponse
	(*ExecRequest)(nil),            // 18: k8shelld.ExecRequest
	(*ExecResponse)(nil),           // 19: k8shelld.ExecResponse
	(*CommandDetails)(nil),         // 20: k8shelld.CommandDetails
	(*UnixSocketRequest)(nil),      // 21: k8shelld.UnixSocketRequest
	(*UnixSocketResponse)(nil),     // 22: k8shelld.UnixSocketResponse
	(*UnixSocketStartRequest)(nil), // 23: k8shelld.UnixSocketStartRequest
	(*CommandMessage)(nil),         // 24: k8shelld.CommandMessage
	(*ListAppsRequest)(nil),        // 25: k8shelld.ListAppsRequest
	(*ListAppsResponse)(nil),       // 26: k8shelld.ListAppsResponse
	(*AppStatus)(nil),              // 27: k8shelld.AppStatus
	(*InstallAppRequest)(nil),      // 28: k8shelld.InstallAppRequest
	(*InstallAppResponse)(nil),     // 29: k8shelld.InstallAppResponse
	(*StartAppRequest)(nil),        // 30: k8shelld.StartAppRequest
	(*StartAppResponse)(nil),       // 31: k8shelld.StartAppResponse
	(*StopAppRequest)(nil),         // 32: k8shelld.StopAppRequest
	(*StopAppResponse)(nil),        // 33: k8shelld.StopAppResponse
	(*GetLogsRequest)(nil),         // 34: k8shelld.GetLogsRequest
	(*GetLogsResponse)(nil),        // 35: k8shelld.GetLogsResponse
	(*GetLogsStreamRequest)(nil),   // 36: k8shelld.GetLogsStreamRequest
	(*GetLogsStreamResponse)(nil),  // 37: k8shelld.GetLogsStreamResponse
}
var file_pkg_api_k8shelld_proto_depIdxs = []int32{
	4,  // 0: k8shelld.SystemInfoResponse.system:type_name -> k8shelld.SystemMetrics
	5,  // 1: k8shelld.SystemInfoResponse.mounts:type_name -> k8shelld.MountUsage
	6,  // 2: k8shelld.SystemInfoResponse.docker:type_name -> k8shelld.DockerUsage
	11, // 3: k8shelld.ShellRequest.start_request:type_name -> k8shelld.ShellStartRequest
	12, // 4: k8shelld.ShellResponse.start_response:type_name -> k8shelld.ShellStartResponse
	16, // 5: k8shelld.PortForwardRequest.destination:type_name -> k8shelld.Destination
	20, // 6: k8shelld.ExecRequest.command_details:type_name -> k8shelld.CommandDetails
	23, // 7: k8shelld.UnixSocketRequest.start_request:type_name -> k8shelld.UnixSocketStartRequest
	0,  // 8: k8shelld.UnixSocketStartRequest.mode:type_name -> k8shelld.UnixSocketMode
	27, // 9: k8shelld.ListAppsResponse.apps:type_name -> k8shelld.AppStatus
	1,  // 10: k8shelld.GetLogsRequest.type:type_name -> k8shelld.LogType
	1,  // 11: k8shelld.GetLogsStreamRequest.type:type_name -> k8shelld.LogType
	7,  // 12: k8shelld.SystemService.Handshake:input_type -> k8shelld.HandshakeRequest
	2,  // 13: k8shelld.SystemService.SystemInfo:input_type -> k8shelld.SystemInfoRequest
	9,  // 14: k8shelld.ShellService.Shell:input_type -> k8shelld.ShellRequest
	13, // 15: k8shelld.ShellService.ResizeTerminal:input_type -> k8shelld.ResizeTerminalRequest
	15, // 16: k8shelld.PortForwardService.PortForward:input_type -> k8shelld.PortForwardRequest
	18, // 17: k8shelld.ExecService.Exec:input_type -> k8shelld.ExecRequest
	21, // 18: k8shelld.UnixSocketService.UnixSocket:input_type -> k8shelld.UnixSocketRequest
	24, // 19: k8shelld.CommandService.CommandListener:input_type -> k8shelld.CommandMessage
	25, // 20: k8shelld.AppService.ListApps:input_type -> k8shelld.ListAppsRequest
	28, // 21: k8shelld.AppService.InstallApp:input_type -> k8shelld.InstallAppRequest
	30, // 22: k8shelld.AppService.StartApp:input_type -> k8shelld.StartAppRequest
	32, // 23: k8shelld.AppService.StopApp:input_type -> k8shelld.StopAppRequest
	34, // 24: k8shelld.AppService.GetLogs:input_type -> k8shelld.GetLogsRequest
	36, // 25: k8shelld.AppService.GetLogsStream:input_type -> k8shelld.GetLogsStreamRequest
	8,  // 26: k8shelld.SystemService.Handshake:output_type -> k8shelld.HandshakeResponse
	3,  // 27: k8shelld.SystemService.SystemInfo:output_type -> k8shelld.SystemInfoResponse
	10, // 28: k8shelld.ShellService.Shell:output_type -> k8shelld.ShellResponse
	14, // 29: k8shelld.ShellService.ResizeTerminal:output_type -> k8shelld.ResizeTerminalResponse
	17, // 30: k8shelld.PortForwardService.PortForward:output_type -> k8shelld.PortForwardResponse
	19, // 31: k8shelld.ExecService.Exec:output_type -> k8shelld.ExecResponse
	22, // 32: k8shelld.UnixSocketService.UnixSocket:output_type -> k8shelld.UnixSocketResponse
	24, // 33: k8shelld.CommandService.CommandListener:output_type -> k8shelld.CommandMessage
	26, // 34: k8shelld.AppService.ListApps:output_type -> k8shelld.ListAppsResponse
	29, // 35: k8shelld.AppService.InstallApp:output_type -> k8shelld.InstallAppResponse
	31, // 36: k8shelld.AppService.StartApp:output_type -> k8shelld.StartAppResponse
	33, // 37: k8shelld.AppService.StopApp:output_type -> k8shelld.StopAppResponse
	35, // 38: k8shelld.AppService.GetLogs:output_type -> k8shelld.GetLogsResponse
	37, // 39: k8shelld.AppService.GetLogsStream:output_type -> k8shelld.GetLogsStreamResponse
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_api_k8shelld_proto_init() }
func file_pkg_api_k8shelld_proto_init() {
	if File_pkg_api_k8shelld_proto != nil {
		return
	}
	file_pkg_api_k8shelld_proto_msgTypes[7].OneofWrappers = []any{
		(*ShellRequest_StartRequest)(nil),
		(*ShellRequest_Data)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[8].OneofWrappers = []any{
		(*ShellResponse_StartResponse)(nil),
		(*ShellResponse_Data)(nil),
		(*ShellResponse_Terminate)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[13].OneofWrappers = []any{
		(*PortForwardRequest_Destination)(nil),
		(*PortForwardRequest_Data)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[16].OneofWrappers = []any{
		(*ExecRequest_CommandDetails)(nil),
		(*ExecRequest_Input)(nil),
		(*ExecRequest_Signal)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[17].OneofWrappers = []any{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
		(*ExecResponse_ExitCode)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[19].OneofWrappers = []any{
		(*UnixSocketRequest_StartRequest)(nil),
		(*UnixSocketRequest_Data)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[22].OneofWrappers = []any{
		(*CommandMessage_Command)(nil),
		(*CommandMessage_Reply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_k8shelld_proto_rawDesc), len(file_pkg_api_k8shelld_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_pkg_api_k8shelld_proto_goTypes,
		DependencyIndexes: file_pkg_api_k8shelld_proto_depIdxs,
		EnumInfos:         file_pkg_api_k8shelld_proto_enumTypes,
		MessageInfos:      file_pkg_api_k8shelld_proto_msgTypes,
	}.Build()
	File_pkg_api_k8shelld_proto = out.File
	file_pkg_api_k8shelld_proto_goTypes = nil
	file_pkg_api_k8shelld_proto_depIdxs = nil
}
