// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/api/k8shelld.proto

package k8shelldpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InfoService_Version_FullMethodName = "/k8shelld.InfoService/Version"
)

// InfoServiceClient is the client API for InfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *** InfoService definition
type InfoServiceClient interface {
	// Version gets the version of the service
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type infoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoServiceClient(cc grpc.ClientConnInterface) InfoServiceClient {
	return &infoServiceClient{cc}
}

func (c *infoServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, InfoService_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoServiceServer is the server API for InfoService service.
// All implementations must embed UnimplementedInfoServiceServer
// for forward compatibility.
//
// *** InfoService definition
type InfoServiceServer interface {
	// Version gets the version of the service
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedInfoServiceServer()
}

// UnimplementedInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInfoServiceServer struct{}

func (UnimplementedInfoServiceServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedInfoServiceServer) mustEmbedUnimplementedInfoServiceServer() {}
func (UnimplementedInfoServiceServer) testEmbeddedByValue()                     {}

// UnsafeInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoServiceServer will
// result in compilation errors.
type UnsafeInfoServiceServer interface {
	mustEmbedUnimplementedInfoServiceServer()
}

func RegisterInfoServiceServer(s grpc.ServiceRegistrar, srv InfoServiceServer) {
	// If the following call pancis, it indicates UnimplementedInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InfoService_ServiceDesc, srv)
}

func _InfoService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoService_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InfoService_ServiceDesc is the grpc.ServiceDesc for InfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k8shelld.InfoService",
	HandlerType: (*InfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _InfoService_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/k8shelld.proto",
}

const (
	InitService_RunInitScripts_FullMethodName = "/k8shelld.InitService/RunInitScripts"
)

// InitServiceClient is the client API for InitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *** InitService definition
type InitServiceClient interface {
	// Workspace initialization
	RunInitScripts(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
}

type initServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInitServiceClient(cc grpc.ClientConnInterface) InitServiceClient {
	return &initServiceClient{cc}
}

func (c *initServiceClient) RunInitScripts(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, InitService_RunInitScripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitServiceServer is the server API for InitService service.
// All implementations must embed UnimplementedInitServiceServer
// for forward compatibility.
//
// *** InitService definition
type InitServiceServer interface {
	// Workspace initialization
	RunInitScripts(context.Context, *InitRequest) (*InitResponse, error)
	mustEmbedUnimplementedInitServiceServer()
}

// UnimplementedInitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInitServiceServer struct{}

func (UnimplementedInitServiceServer) RunInitScripts(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunInitScripts not implemented")
}
func (UnimplementedInitServiceServer) mustEmbedUnimplementedInitServiceServer() {}
func (UnimplementedInitServiceServer) testEmbeddedByValue()                     {}

// UnsafeInitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InitServiceServer will
// result in compilation errors.
type UnsafeInitServiceServer interface {
	mustEmbedUnimplementedInitServiceServer()
}

func RegisterInitServiceServer(s grpc.ServiceRegistrar, srv InitServiceServer) {
	// If the following call pancis, it indicates UnimplementedInitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InitService_ServiceDesc, srv)
}

func _InitService_RunInitScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).RunInitScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_RunInitScripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).RunInitScripts(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InitService_ServiceDesc is the grpc.ServiceDesc for InitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k8shelld.InitService",
	HandlerType: (*InitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunInitScripts",
			Handler:    _InitService_RunInitScripts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/k8shelld.proto",
}

const (
	RemoteOSService_Shell_FullMethodName          = "/k8shelld.RemoteOSService/Shell"
	RemoteOSService_ResizeTerminal_FullMethodName = "/k8shelld.RemoteOSService/ResizeTerminal"
	RemoteOSService_PortForward_FullMethodName    = "/k8shelld.RemoteOSService/PortForward"
	RemoteOSService_Exec_FullMethodName           = "/k8shelld.RemoteOSService/Exec"
	RemoteOSService_UnixSocket_FullMethodName     = "/k8shelld.RemoteOSService/UnixSocket"
)

// RemoteOSServiceClient is the client API for RemoteOSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *** RemoteOSService definition
type RemoteOSServiceClient interface {
	// Shell starts a shell session
	Shell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellRequest, ShellResponse], error)
	// ResizeTerminal resizes the terminal in a shell session
	ResizeTerminal(ctx context.Context, in *ResizeTerminalRequest, opts ...grpc.CallOption) (*ResizeTerminalResponse, error)
	// PortForward forwards a port to the specified destination IP and port
	PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PortForwardRequest, PortForwardResponse], error)
	// Exec executes a command
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error)
	// UnixSocket reads/writes to a Unix socket in the remote OS
	// This is primarily used for SSH agent forwarding
	UnixSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnixSocketRequest, UnixSocketResponse], error)
}

type remoteOSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteOSServiceClient(cc grpc.ClientConnInterface) RemoteOSServiceClient {
	return &remoteOSServiceClient{cc}
}

func (c *remoteOSServiceClient) Shell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellRequest, ShellResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteOSService_ServiceDesc.Streams[0], RemoteOSService_Shell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShellRequest, ShellResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteOSService_ShellClient = grpc.BidiStreamingClient[ShellRequest, ShellResponse]

func (c *remoteOSServiceClient) ResizeTerminal(ctx context.Context, in *ResizeTerminalRequest, opts ...grpc.CallOption) (*ResizeTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeTerminalResponse)
	err := c.cc.Invoke(ctx, RemoteOSService_ResizeTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteOSServiceClient) PortForward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PortForwardRequest, PortForwardResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteOSService_ServiceDesc.Streams[1], RemoteOSService_PortForward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PortForwardRequest, PortForwardResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteOSService_PortForwardClient = grpc.BidiStreamingClient[PortForwardRequest, PortForwardResponse]

func (c *remoteOSServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteOSService_ServiceDesc.Streams[2], RemoteOSService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteOSService_ExecClient = grpc.BidiStreamingClient[ExecRequest, ExecResponse]

func (c *remoteOSServiceClient) UnixSocket(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UnixSocketRequest, UnixSocketResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteOSService_ServiceDesc.Streams[3], RemoteOSService_UnixSocket_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UnixSocketRequest, UnixSocketResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteOSService_UnixSocketClient = grpc.BidiStreamingClient[UnixSocketRequest, UnixSocketResponse]

// RemoteOSServiceServer is the server API for RemoteOSService service.
// All implementations must embed UnimplementedRemoteOSServiceServer
// for forward compatibility.
//
// *** RemoteOSService definition
type RemoteOSServiceServer interface {
	// Shell starts a shell session
	Shell(grpc.BidiStreamingServer[ShellRequest, ShellResponse]) error
	// ResizeTerminal resizes the terminal in a shell session
	ResizeTerminal(context.Context, *ResizeTerminalRequest) (*ResizeTerminalResponse, error)
	// PortForward forwards a port to the specified destination IP and port
	PortForward(grpc.BidiStreamingServer[PortForwardRequest, PortForwardResponse]) error
	// Exec executes a command
	Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error
	// UnixSocket reads/writes to a Unix socket in the remote OS
	// This is primarily used for SSH agent forwarding
	UnixSocket(grpc.BidiStreamingServer[UnixSocketRequest, UnixSocketResponse]) error
	mustEmbedUnimplementedRemoteOSServiceServer()
}

// UnimplementedRemoteOSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteOSServiceServer struct{}

func (UnimplementedRemoteOSServiceServer) Shell(grpc.BidiStreamingServer[ShellRequest, ShellResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Shell not implemented")
}
func (UnimplementedRemoteOSServiceServer) ResizeTerminal(context.Context, *ResizeTerminalRequest) (*ResizeTerminalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizeTerminal not implemented")
}
func (UnimplementedRemoteOSServiceServer) PortForward(grpc.BidiStreamingServer[PortForwardRequest, PortForwardResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PortForward not implemented")
}
func (UnimplementedRemoteOSServiceServer) Exec(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedRemoteOSServiceServer) UnixSocket(grpc.BidiStreamingServer[UnixSocketRequest, UnixSocketResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UnixSocket not implemented")
}
func (UnimplementedRemoteOSServiceServer) mustEmbedUnimplementedRemoteOSServiceServer() {}
func (UnimplementedRemoteOSServiceServer) testEmbeddedByValue()                         {}

// UnsafeRemoteOSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteOSServiceServer will
// result in compilation errors.
type UnsafeRemoteOSServiceServer interface {
	mustEmbedUnimplementedRemoteOSServiceServer()
}

func RegisterRemoteOSServiceServer(s grpc.ServiceRegistrar, srv RemoteOSServiceServer) {
	// If the following call pancis, it indicates UnimplementedRemoteOSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteOSService_ServiceDesc, srv)
}

func _RemoteOSService_Shell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteOSServiceServer).Shell(&grpc.GenericServerStream[ShellRequest, ShellResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteOSService_ShellServer = grpc.BidiStreamingServer[ShellRequest, ShellResponse]

func _RemoteOSService_ResizeTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteOSServiceServer).ResizeTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteOSService_ResizeTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteOSServiceServer).ResizeTerminal(ctx, req.(*ResizeTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteOSService_PortForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteOSServiceServer).PortForward(&grpc.GenericServerStream[PortForwardRequest, PortForwardResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteOSService_PortForwardServer = grpc.BidiStreamingServer[PortForwardRequest, PortForwardResponse]

func _RemoteOSService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteOSServiceServer).Exec(&grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteOSService_ExecServer = grpc.BidiStreamingServer[ExecRequest, ExecResponse]

func _RemoteOSService_UnixSocket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteOSServiceServer).UnixSocket(&grpc.GenericServerStream[UnixSocketRequest, UnixSocketResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteOSService_UnixSocketServer = grpc.BidiStreamingServer[UnixSocketRequest, UnixSocketResponse]

// RemoteOSService_ServiceDesc is the grpc.ServiceDesc for RemoteOSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteOSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k8shelld.RemoteOSService",
	HandlerType: (*RemoteOSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResizeTerminal",
			Handler:    _RemoteOSService_ResizeTerminal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Shell",
			Handler:       _RemoteOSService_Shell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PortForward",
			Handler:       _RemoteOSService_PortForward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _RemoteOSService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UnixSocket",
			Handler:       _RemoteOSService_UnixSocket_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/api/k8shelld.proto",
}
