// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/api/k8shelld.proto

package k8shelldpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mode for Unix socket operation
type UnixSocketMode int32

const (
	UnixSocketMode_UNIX_SOCKET_MODE_LISTEN UnixSocketMode = 0
	UnixSocketMode_UNIX_SOCKET_MODE_DIAL   UnixSocketMode = 1
)

// Enum value maps for UnixSocketMode.
var (
	UnixSocketMode_name = map[int32]string{
		0: "UNIX_SOCKET_MODE_LISTEN",
		1: "UNIX_SOCKET_MODE_DIAL",
	}
	UnixSocketMode_value = map[string]int32{
		"UNIX_SOCKET_MODE_LISTEN": 0,
		"UNIX_SOCKET_MODE_DIAL":   1,
	}
)

func (x UnixSocketMode) Enum() *UnixSocketMode {
	p := new(UnixSocketMode)
	*p = x
	return p
}

func (x UnixSocketMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnixSocketMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_k8shelld_proto_enumTypes[0].Descriptor()
}

func (UnixSocketMode) Type() protoreflect.EnumType {
	return &file_pkg_api_k8shelld_proto_enumTypes[0]
}

func (x UnixSocketMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnixSocketMode.Descriptor instead.
func (UnixSocketMode) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{0}
}

// Which log to return
type LogType int32

const (
	LogType_LOG_TYPE_APP     LogType = 0 // runtime app log
	LogType_LOG_TYPE_INSTALL LogType = 1 // install log
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_TYPE_APP",
		1: "LOG_TYPE_INSTALL",
	}
	LogType_value = map[string]int32{
		"LOG_TYPE_APP":     0,
		"LOG_TYPE_INSTALL": 1,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_k8shelld_proto_enumTypes[1].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_pkg_api_k8shelld_proto_enumTypes[1]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{1}
}

// HandshakeRequest message
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	EnvVars       []string               `protobuf:"bytes,7,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *HandshakeRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HandshakeRequest) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

// User to be used to setup workspace
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,4,opt,name=gid,proto3" json:"gid,omitempty"`
	UserToken     string                 `protobuf:"bytes,5,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *User) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *User) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *User) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

// HandshakeResponse message
type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ShellRequest message
type ShellRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ShellRequest_StartRequest
	//	*ShellRequest_Data
	Request       isShellRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellRequest) Reset() {
	*x = ShellRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellRequest) ProtoMessage() {}

func (x *ShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellRequest.ProtoReflect.Descriptor instead.
func (*ShellRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{3}
}

func (x *ShellRequest) GetRequest() isShellRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ShellRequest) GetStartRequest() *ShellStartRequest {
	if x != nil {
		if x, ok := x.Request.(*ShellRequest_StartRequest); ok {
			return x.StartRequest
		}
	}
	return nil
}

func (x *ShellRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*ShellRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isShellRequest_Request interface {
	isShellRequest_Request()
}

type ShellRequest_StartRequest struct {
	StartRequest *ShellStartRequest `protobuf:"bytes,1,opt,name=start_request,json=startRequest,proto3,oneof"` // Start shell request
}

type ShellRequest_Data struct {
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"` // Data to send to the shell
}

func (*ShellRequest_StartRequest) isShellRequest_Request() {}

func (*ShellRequest_Data) isShellRequest_Request() {}

// ShellRequest message
type ShellResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ShellResponse_Data
	//	*ShellResponse_Terminate
	Response      isShellResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellResponse) Reset() {
	*x = ShellResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResponse) ProtoMessage() {}

func (x *ShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResponse.ProtoReflect.Descriptor instead.
func (*ShellResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{4}
}

func (x *ShellResponse) GetResponse() isShellResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ShellResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Response.(*ShellResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ShellResponse) GetTerminate() bool {
	if x != nil {
		if x, ok := x.Response.(*ShellResponse_Terminate); ok {
			return x.Terminate
		}
	}
	return false
}

type isShellResponse_Response interface {
	isShellResponse_Response()
}

type ShellResponse_Data struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof"` // Data to send to the shell
}

type ShellResponse_Terminate struct {
	Terminate bool `protobuf:"varint,2,opt,name=terminate,proto3,oneof"` // Terminate the shell session
}

func (*ShellResponse_Data) isShellResponse_Response() {}

func (*ShellResponse_Terminate) isShellResponse_Response() {}

// ShellStartRequest message
type ShellStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdShell      string                 `protobuf:"bytes,1,opt,name=cmdShell,proto3" json:"cmdShell,omitempty"`     // Command to run the shell
	SetEnvVars    []string               `protobuf:"bytes,2,rep,name=setEnvVars,proto3" json:"setEnvVars,omitempty"` // Environment variables to be set in the the shell
	UsePty        bool                   `protobuf:"varint,3,opt,name=usePty,proto3" json:"usePty,omitempty"`        // True to use a pseudo-terminal
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`          // Terminal width
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`        // Terminal height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellStartRequest) Reset() {
	*x = ShellStartRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStartRequest) ProtoMessage() {}

func (x *ShellStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStartRequest.ProtoReflect.Descriptor instead.
func (*ShellStartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{5}
}

func (x *ShellStartRequest) GetCmdShell() string {
	if x != nil {
		return x.CmdShell
	}
	return ""
}

func (x *ShellStartRequest) GetSetEnvVars() []string {
	if x != nil {
		return x.SetEnvVars
	}
	return nil
}

func (x *ShellStartRequest) GetUsePty() bool {
	if x != nil {
		return x.UsePty
	}
	return false
}

func (x *ShellStartRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ShellStartRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// ResizeTerminalRequest message
type ResizeTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`   // Terminal width
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"` // Terminal height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTerminalRequest) Reset() {
	*x = ResizeTerminalRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTerminalRequest) ProtoMessage() {}

func (x *ResizeTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTerminalRequest.ProtoReflect.Descriptor instead.
func (*ResizeTerminalRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{6}
}

func (x *ResizeTerminalRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResizeTerminalRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// ResizeTerminalResponse message
type ResizeTerminalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTerminalResponse) Reset() {
	*x = ResizeTerminalResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTerminalResponse) ProtoMessage() {}

func (x *ResizeTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTerminalResponse.ProtoReflect.Descriptor instead.
func (*ResizeTerminalResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{7}
}

// Request for the PortForward operation
type PortForwardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*PortForwardRequest_Destination
	//	*PortForwardRequest_Data
	Request       isPortForwardRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardRequest) Reset() {
	*x = PortForwardRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardRequest) ProtoMessage() {}

func (x *PortForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardRequest.ProtoReflect.Descriptor instead.
func (*PortForwardRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{8}
}

func (x *PortForwardRequest) GetRequest() isPortForwardRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PortForwardRequest) GetDestination() *Destination {
	if x != nil {
		if x, ok := x.Request.(*PortForwardRequest_Destination); ok {
			return x.Destination
		}
	}
	return nil
}

func (x *PortForwardRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*PortForwardRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPortForwardRequest_Request interface {
	isPortForwardRequest_Request()
}

type PortForwardRequest_Destination struct {
	Destination *Destination `protobuf:"bytes,1,opt,name=destination,proto3,oneof"` // Destination details
}

type PortForwardRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Data to send to the destination
}

func (*PortForwardRequest_Destination) isPortForwardRequest_Request() {}

func (*PortForwardRequest_Data) isPortForwardRequest_Request() {}

// Destination details message
type Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`      // Destination IP address
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // Destination port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{9}
}

func (x *Destination) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Destination) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Response for the PortForward operation
type PortForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Data received from the destination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardResponse) Reset() {
	*x = PortForwardResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardResponse) ProtoMessage() {}

func (x *PortForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardResponse.ProtoReflect.Descriptor instead.
func (*PortForwardResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{10}
}

func (x *PortForwardResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request for the Exec operation
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ExecRequest_CommandDetails
	//	*ExecRequest_Input
	//	*ExecRequest_Signal
	Request       isExecRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{11}
}

func (x *ExecRequest) GetRequest() isExecRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecRequest) GetCommandDetails() *CommandDetails {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_CommandDetails); ok {
			return x.CommandDetails
		}
	}
	return nil
}

func (x *ExecRequest) GetInput() []byte {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ExecRequest) GetSignal() string {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_Signal); ok {
			return x.Signal
		}
	}
	return ""
}

type isExecRequest_Request interface {
	isExecRequest_Request()
}

type ExecRequest_CommandDetails struct {
	CommandDetails *CommandDetails `protobuf:"bytes,1,opt,name=command_details,json=commandDetails,proto3,oneof"` // Command details including command and shell binary
}

type ExecRequest_Input struct {
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3,oneof"` // Input to send to the command
}

type ExecRequest_Signal struct {
	Signal string `protobuf:"bytes,3,opt,name=signal,proto3,oneof"` // Signal to send to the command
}

func (*ExecRequest_CommandDetails) isExecRequest_Request() {}

func (*ExecRequest_Input) isExecRequest_Request() {}

func (*ExecRequest_Signal) isExecRequest_Request() {}

// Response for the Exec operation
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	//	*ExecResponse_ExitCode
	Response      isExecResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{12}
}

func (x *ExecResponse) GetResponse() isExecResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecResponse_Response interface {
	isExecResponse_Response()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"` // Standard output
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"` // Standard error
}

type ExecResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"` // Exit code when the process exits
}

func (*ExecResponse_Stdout) isExecResponse_Response() {}

func (*ExecResponse_Stderr) isExecResponse_Response() {}

func (*ExecResponse_ExitCode) isExecResponse_Response() {}

// Command details message
type CommandDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                            // Initial command with arguments
	ShellBinary   string                 `protobuf:"bytes,2,opt,name=shell_binary,json=shellBinary,proto3" json:"shell_binary,omitempty"` // Optional shell binary to use (e.g., "/bin/sh"), empty for none
	EnvVars       []string               `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`             // Environment variables to be set for the command
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDetails) Reset() {
	*x = CommandDetails{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDetails) ProtoMessage() {}

func (x *CommandDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDetails.ProtoReflect.Descriptor instead.
func (*CommandDetails) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{13}
}

func (x *CommandDetails) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandDetails) GetShellBinary() string {
	if x != nil {
		return x.ShellBinary
	}
	return ""
}

func (x *CommandDetails) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

// Request for the UnixSocket operation
type UnixSocketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*UnixSocketRequest_StartRequest
	//	*UnixSocketRequest_Data
	Request       isUnixSocketRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixSocketRequest) Reset() {
	*x = UnixSocketRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketRequest) ProtoMessage() {}

func (x *UnixSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocketRequest.ProtoReflect.Descriptor instead.
func (*UnixSocketRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{14}
}

func (x *UnixSocketRequest) GetRequest() isUnixSocketRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *UnixSocketRequest) GetStartRequest() *UnixSocketStartRequest {
	if x != nil {
		if x, ok := x.Request.(*UnixSocketRequest_StartRequest); ok {
			return x.StartRequest
		}
	}
	return nil
}

func (x *UnixSocketRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*UnixSocketRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUnixSocketRequest_Request interface {
	isUnixSocketRequest_Request()
}

type UnixSocketRequest_StartRequest struct {
	StartRequest *UnixSocketStartRequest `protobuf:"bytes,1,opt,name=start_request,json=startRequest,proto3,oneof"` // Start Unix socket request
}

type UnixSocketRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // Data to send to the Unix socket
}

func (*UnixSocketRequest_StartRequest) isUnixSocketRequest_Request() {}

func (*UnixSocketRequest_Data) isUnixSocketRequest_Request() {}

// Response for the UnixSocket operation
type UnixSocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Data to send to the Unix socket
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixSocketResponse) Reset() {
	*x = UnixSocketResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketResponse) ProtoMessage() {}

func (x *UnixSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocketResponse.ProtoReflect.Descriptor instead.
func (*UnixSocketResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{15}
}

func (x *UnixSocketResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UnixSocketStartRequest message
type UnixSocketStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          UnixSocketMode         `protobuf:"varint,1,opt,name=mode,proto3,enum=k8shelld.UnixSocketMode" json:"mode,omitempty"`
	SocketPath    string                 `protobuf:"bytes,2,opt,name=socketPath,proto3" json:"socketPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnixSocketStartRequest) Reset() {
	*x = UnixSocketStartRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnixSocketStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnixSocketStartRequest) ProtoMessage() {}

func (x *UnixSocketStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnixSocketStartRequest.ProtoReflect.Descriptor instead.
func (*UnixSocketStartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{16}
}

func (x *UnixSocketStartRequest) GetMode() UnixSocketMode {
	if x != nil {
		return x.Mode
	}
	return UnixSocketMode_UNIX_SOCKET_MODE_LISTEN
}

func (x *UnixSocketStartRequest) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

type ListAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{17}
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*AppStatus           `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{18}
}

func (x *ListAppsResponse) GetApps() []*AppStatus {
	if x != nil {
		return x.Apps
	}
	return nil
}

type AppStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	Age           string                 `protobuf:"bytes,6,opt,name=age,proto3" json:"age,omitempty"`
	Restarts      int32                  `protobuf:"varint,7,opt,name=restarts,proto3" json:"restarts,omitempty"`
	Protocol      string                 `protobuf:"bytes,8,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppStatus) Reset() {
	*x = AppStatus{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppStatus) ProtoMessage() {}

func (x *AppStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppStatus.ProtoReflect.Descriptor instead.
func (*AppStatus) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{19}
}

func (x *AppStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AppStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AppStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AppStatus) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AppStatus) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *AppStatus) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *AppStatus) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type InstallAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppRequest) Reset() {
	*x = InstallAppRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppRequest) ProtoMessage() {}

func (x *InstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppRequest.ProtoReflect.Descriptor instead.
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{20}
}

func (x *InstallAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstallAppRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type InstallAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppResponse) Reset() {
	*x = InstallAppResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppResponse) ProtoMessage() {}

func (x *InstallAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppResponse.ProtoReflect.Descriptor instead.
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{21}
}

type StartAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAppRequest) Reset() {
	*x = StartAppRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAppRequest) ProtoMessage() {}

func (x *StartAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAppRequest.ProtoReflect.Descriptor instead.
func (*StartAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{22}
}

func (x *StartAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StartAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAppResponse) Reset() {
	*x = StartAppResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAppResponse) ProtoMessage() {}

func (x *StartAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAppResponse.ProtoReflect.Descriptor instead.
func (*StartAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{23}
}

type StopAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAppRequest) Reset() {
	*x = StopAppRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAppRequest) ProtoMessage() {}

func (x *StopAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAppRequest.ProtoReflect.Descriptor instead.
func (*StopAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{24}
}

func (x *StopAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAppResponse) Reset() {
	*x = StopAppResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAppResponse) ProtoMessage() {}

func (x *StopAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAppResponse.ProtoReflect.Descriptor instead.
func (*StopAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{25}
}

type GetLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          LogType                `protobuf:"varint,2,opt,name=type,proto3,enum=k8shelld.LogType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsRequest) Reset() {
	*x = GetLogsRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsRequest) ProtoMessage() {}

func (x *GetLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLogsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{26}
}

func (x *GetLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLogsRequest) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_LOG_TYPE_APP
}

type GetLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsResponse) Reset() {
	*x = GetLogsResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsResponse) ProtoMessage() {}

func (x *GetLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLogsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{27}
}

func (x *GetLogsResponse) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type GetLogsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          LogType                `protobuf:"varint,2,opt,name=type,proto3,enum=k8shelld.LogType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsStreamRequest) Reset() {
	*x = GetLogsStreamRequest{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsStreamRequest) ProtoMessage() {}

func (x *GetLogsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsStreamRequest.ProtoReflect.Descriptor instead.
func (*GetLogsStreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{28}
}

func (x *GetLogsStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetLogsStreamRequest) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_LOG_TYPE_APP
}

type GetLogsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogsStreamResponse) Reset() {
	*x = GetLogsStreamResponse{}
	mi := &file_pkg_api_k8shelld_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogsStreamResponse) ProtoMessage() {}

func (x *GetLogsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_k8shelld_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogsStreamResponse.ProtoReflect.Descriptor instead.
func (*GetLogsStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_k8shelld_proto_rawDescGZIP(), []int{29}
}

func (x *GetLogsStreamResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_pkg_api_k8shelld_proto protoreflect.FileDescriptor

const file_pkg_api_k8shelld_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/api/k8shelld.proto\x12\bk8shelld\"x\n" +
	"\x10HandshakeRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12\"\n" +
	"\x04user\x18\x02 \x01(\v2\x0e.k8shelld.UserR\x04user\x12\x19\n" +
	"\benv_vars\x18\a \x03(\tR\aenvVars\"\x81\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\rR\x03gid\x12\x1d\n" +
	"\n" +
	"user_token\x18\x05 \x01(\tR\tuserToken\"p\n" +
	"\x11HandshakeResponse\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"s\n" +
	"\fShellRequest\x12B\n" +
	"\rstart_request\x18\x01 \x01(\v2\x1b.k8shelld.ShellStartRequestH\x00R\fstartRequest\x12\x14\n" +
	"\x04data\x18\x03 \x01(\fH\x00R\x04dataB\t\n" +
	"\arequest\"Q\n" +
	"\rShellResponse\x12\x14\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x12\x1e\n" +
	"\tterminate\x18\x02 \x01(\bH\x00R\tterminateB\n" +
	"\n" +
	"\bresponse\"\x95\x01\n" +
	"\x11ShellStartRequest\x12\x1a\n" +
	"\bcmdShell\x18\x01 \x01(\tR\bcmdShell\x12\x1e\n" +
	"\n" +
	"setEnvVars\x18\x02 \x03(\tR\n" +
	"setEnvVars\x12\x16\n" +
	"\x06usePty\x18\x03 \x01(\bR\x06usePty\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\"E\n" +
	"\x15ResizeTerminalRequest\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\"\x18\n" +
	"\x16ResizeTerminalResponse\"p\n" +
	"\x12PortForwardRequest\x129\n" +
	"\vdestination\x18\x01 \x01(\v2\x15.k8shelld.DestinationH\x00R\vdestination\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\arequest\"1\n" +
	"\vDestination\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\")\n" +
	"\x13PortForwardResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x8f\x01\n" +
	"\vExecRequest\x12C\n" +
	"\x0fcommand_details\x18\x01 \x01(\v2\x18.k8shelld.CommandDetailsH\x00R\x0ecommandDetails\x12\x16\n" +
	"\x05input\x18\x02 \x01(\fH\x00R\x05input\x12\x18\n" +
	"\x06signal\x18\x03 \x01(\tH\x00R\x06signalB\t\n" +
	"\arequest\"m\n" +
	"\fExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\n" +
	"\n" +
	"\bresponse\"h\n" +
	"\x0eCommandDetails\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12!\n" +
	"\fshell_binary\x18\x02 \x01(\tR\vshellBinary\x12\x19\n" +
	"\benv_vars\x18\x03 \x03(\tR\aenvVars\"}\n" +
	"\x11UnixSocketRequest\x12G\n" +
	"\rstart_request\x18\x01 \x01(\v2 .k8shelld.UnixSocketStartRequestH\x00R\fstartRequest\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\arequest\"(\n" +
	"\x12UnixSocketResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"f\n" +
	"\x16UnixSocketStartRequest\x12,\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x18.k8shelld.UnixSocketModeR\x04mode\x12\x1e\n" +
	"\n" +
	"socketPath\x18\x02 \x01(\tR\n" +
	"socketPath\"\x11\n" +
	"\x0fListAppsRequest\";\n" +
	"\x10ListAppsResponse\x12'\n" +
	"\x04apps\x18\x01 \x03(\v2\x13.k8shelld.AppStatusR\x04apps\"\xc1\x01\n" +
	"\tAppStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03age\x18\x06 \x01(\tR\x03age\x12\x1a\n" +
	"\brestarts\x18\a \x01(\x05R\brestarts\x12\x1a\n" +
	"\bprotocol\x18\b \x01(\tR\bprotocol\"=\n" +
	"\x11InstallAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x14\n" +
	"\x12InstallAppResponse\"%\n" +
	"\x0fStartAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x12\n" +
	"\x10StartAppResponse\"$\n" +
	"\x0eStopAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x11\n" +
	"\x0fStopAppResponse\"K\n" +
	"\x0eGetLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.k8shelld.LogTypeR\x04type\"#\n" +
	"\x0fGetLogsResponse\x12\x10\n" +
	"\x03log\x18\x01 \x01(\tR\x03log\"Q\n" +
	"\x14GetLogsStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.k8shelld.LogTypeR\x04type\"+\n" +
	"\x15GetLogsStreamResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line*H\n" +
	"\x0eUnixSocketMode\x12\x1b\n" +
	"\x17UNIX_SOCKET_MODE_LISTEN\x10\x00\x12\x19\n" +
	"\x15UNIX_SOCKET_MODE_DIAL\x10\x01*1\n" +
	"\aLogType\x12\x10\n" +
	"\fLOG_TYPE_APP\x10\x00\x12\x14\n" +
	"\x10LOG_TYPE_INSTALL\x10\x012U\n" +
	"\rSystemService\x12D\n" +
	"\tHandshake\x12\x1a.k8shelld.HandshakeRequest\x1a\x1b.k8shelld.HandshakeResponse2\xa1\x01\n" +
	"\fShellService\x12<\n" +
	"\x05Shell\x12\x16.k8shelld.ShellRequest\x1a\x17.k8shelld.ShellResponse(\x010\x01\x12S\n" +
	"\x0eResizeTerminal\x12\x1f.k8shelld.ResizeTerminalRequest\x1a .k8shelld.ResizeTerminalResponse2d\n" +
	"\x12PortForwardService\x12N\n" +
	"\vPortForward\x12\x1c.k8shelld.PortForwardRequest\x1a\x1d.k8shelld.PortForwardResponse(\x010\x012H\n" +
	"\vExecService\x129\n" +
	"\x04Exec\x12\x15.k8shelld.ExecRequest\x1a\x16.k8shelld.ExecResponse(\x010\x012`\n" +
	"\x11UnixSocketService\x12K\n" +
	"\n" +
	"UnixSocket\x12\x1b.k8shelld.UnixSocketRequest\x1a\x1c.k8shelld.UnixSocketResponse(\x010\x012\xaf\x03\n" +
	"\n" +
	"AppService\x12A\n" +
	"\bListApps\x12\x19.k8shelld.ListAppsRequest\x1a\x1a.k8shelld.ListAppsResponse\x12G\n" +
	"\n" +
	"InstallApp\x12\x1b.k8shelld.InstallAppRequest\x1a\x1c.k8shelld.InstallAppResponse\x12A\n" +
	"\bStartApp\x12\x19.k8shelld.StartAppRequest\x1a\x1a.k8shelld.StartAppResponse\x12>\n" +
	"\aStopApp\x12\x18.k8shelld.StopAppRequest\x1a\x19.k8shelld.StopAppResponse\x12>\n" +
	"\aGetLogs\x12\x18.k8shelld.GetLogsRequest\x1a\x19.k8shelld.GetLogsResponse\x12R\n" +
	"\rGetLogsStream\x12\x1e.k8shelld.GetLogsStreamRequest\x1a\x1f.k8shelld.GetLogsStreamResponse0\x01B>Z<github.com/k8shell-io/k8shelld/pkg/api/k8shelldpb;k8shelldpbb\x06proto3"

var (
	file_pkg_api_k8shelld_proto_rawDescOnce sync.Once
	file_pkg_api_k8shelld_proto_rawDescData []byte
)

func file_pkg_api_k8shelld_proto_rawDescGZIP() []byte {
	file_pkg_api_k8shelld_proto_rawDescOnce.Do(func() {
		file_pkg_api_k8shelld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_k8shelld_proto_rawDesc), len(file_pkg_api_k8shelld_proto_rawDesc)))
	})
	return file_pkg_api_k8shelld_proto_rawDescData
}

var file_pkg_api_k8shelld_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_api_k8shelld_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_pkg_api_k8shelld_proto_goTypes = []any{
	(UnixSocketMode)(0),            // 0: k8shelld.UnixSocketMode
	(LogType)(0),                   // 1: k8shelld.LogType
	(*HandshakeRequest)(nil),       // 2: k8shelld.HandshakeRequest
	(*User)(nil),                   // 3: k8shelld.User
	(*HandshakeResponse)(nil),      // 4: k8shelld.HandshakeResponse
	(*ShellRequest)(nil),           // 5: k8shelld.ShellRequest
	(*ShellResponse)(nil),          // 6: k8shelld.ShellResponse
	(*ShellStartRequest)(nil),      // 7: k8shelld.ShellStartRequest
	(*ResizeTerminalRequest)(nil),  // 8: k8shelld.ResizeTerminalRequest
	(*ResizeTerminalResponse)(nil), // 9: k8shelld.ResizeTerminalResponse
	(*PortForwardRequest)(nil),     // 10: k8shelld.PortForwardRequest
	(*Destination)(nil),            // 11: k8shelld.Destination
	(*PortForwardResponse)(nil),    // 12: k8shelld.PortForwardResponse
	(*ExecRequest)(nil),            // 13: k8shelld.ExecRequest
	(*ExecResponse)(nil),           // 14: k8shelld.ExecResponse
	(*CommandDetails)(nil),         // 15: k8shelld.CommandDetails
	(*UnixSocketRequest)(nil),      // 16: k8shelld.UnixSocketRequest
	(*UnixSocketResponse)(nil),     // 17: k8shelld.UnixSocketResponse
	(*UnixSocketStartRequest)(nil), // 18: k8shelld.UnixSocketStartRequest
	(*ListAppsRequest)(nil),        // 19: k8shelld.ListAppsRequest
	(*ListAppsResponse)(nil),       // 20: k8shelld.ListAppsResponse
	(*AppStatus)(nil),              // 21: k8shelld.AppStatus
	(*InstallAppRequest)(nil),      // 22: k8shelld.InstallAppRequest
	(*InstallAppResponse)(nil),     // 23: k8shelld.InstallAppResponse
	(*StartAppRequest)(nil),        // 24: k8shelld.StartAppRequest
	(*StartAppResponse)(nil),       // 25: k8shelld.StartAppResponse
	(*StopAppRequest)(nil),         // 26: k8shelld.StopAppRequest
	(*StopAppResponse)(nil),        // 27: k8shelld.StopAppResponse
	(*GetLogsRequest)(nil),         // 28: k8shelld.GetLogsRequest
	(*GetLogsResponse)(nil),        // 29: k8shelld.GetLogsResponse
	(*GetLogsStreamRequest)(nil),   // 30: k8shelld.GetLogsStreamRequest
	(*GetLogsStreamResponse)(nil),  // 31: k8shelld.GetLogsStreamResponse
}
var file_pkg_api_k8shelld_proto_depIdxs = []int32{
	3,  // 0: k8shelld.HandshakeRequest.user:type_name -> k8shelld.User
	7,  // 1: k8shelld.ShellRequest.start_request:type_name -> k8shelld.ShellStartRequest
	11, // 2: k8shelld.PortForwardRequest.destination:type_name -> k8shelld.Destination
	15, // 3: k8shelld.ExecRequest.command_details:type_name -> k8shelld.CommandDetails
	18, // 4: k8shelld.UnixSocketRequest.start_request:type_name -> k8shelld.UnixSocketStartRequest
	0,  // 5: k8shelld.UnixSocketStartRequest.mode:type_name -> k8shelld.UnixSocketMode
	21, // 6: k8shelld.ListAppsResponse.apps:type_name -> k8shelld.AppStatus
	1,  // 7: k8shelld.GetLogsRequest.type:type_name -> k8shelld.LogType
	1,  // 8: k8shelld.GetLogsStreamRequest.type:type_name -> k8shelld.LogType
	2,  // 9: k8shelld.SystemService.Handshake:input_type -> k8shelld.HandshakeRequest
	5,  // 10: k8shelld.ShellService.Shell:input_type -> k8shelld.ShellRequest
	8,  // 11: k8shelld.ShellService.ResizeTerminal:input_type -> k8shelld.ResizeTerminalRequest
	10, // 12: k8shelld.PortForwardService.PortForward:input_type -> k8shelld.PortForwardRequest
	13, // 13: k8shelld.ExecService.Exec:input_type -> k8shelld.ExecRequest
	16, // 14: k8shelld.UnixSocketService.UnixSocket:input_type -> k8shelld.UnixSocketRequest
	19, // 15: k8shelld.AppService.ListApps:input_type -> k8shelld.ListAppsRequest
	22, // 16: k8shelld.AppService.InstallApp:input_type -> k8shelld.InstallAppRequest
	24, // 17: k8shelld.AppService.StartApp:input_type -> k8shelld.StartAppRequest
	26, // 18: k8shelld.AppService.StopApp:input_type -> k8shelld.StopAppRequest
	28, // 19: k8shelld.AppService.GetLogs:input_type -> k8shelld.GetLogsRequest
	30, // 20: k8shelld.AppService.GetLogsStream:input_type -> k8shelld.GetLogsStreamRequest
	4,  // 21: k8shelld.SystemService.Handshake:output_type -> k8shelld.HandshakeResponse
	6,  // 22: k8shelld.ShellService.Shell:output_type -> k8shelld.ShellResponse
	9,  // 23: k8shelld.ShellService.ResizeTerminal:output_type -> k8shelld.ResizeTerminalResponse
	12, // 24: k8shelld.PortForwardService.PortForward:output_type -> k8shelld.PortForwardResponse
	14, // 25: k8shelld.ExecService.Exec:output_type -> k8shelld.ExecResponse
	17, // 26: k8shelld.UnixSocketService.UnixSocket:output_type -> k8shelld.UnixSocketResponse
	20, // 27: k8shelld.AppService.ListApps:output_type -> k8shelld.ListAppsResponse
	23, // 28: k8shelld.AppService.InstallApp:output_type -> k8shelld.InstallAppResponse
	25, // 29: k8shelld.AppService.StartApp:output_type -> k8shelld.StartAppResponse
	27, // 30: k8shelld.AppService.StopApp:output_type -> k8shelld.StopAppResponse
	29, // 31: k8shelld.AppService.GetLogs:output_type -> k8shelld.GetLogsResponse
	31, // 32: k8shelld.AppService.GetLogsStream:output_type -> k8shelld.GetLogsStreamResponse
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_api_k8shelld_proto_init() }
func file_pkg_api_k8shelld_proto_init() {
	if File_pkg_api_k8shelld_proto != nil {
		return
	}
	file_pkg_api_k8shelld_proto_msgTypes[3].OneofWrappers = []any{
		(*ShellRequest_StartRequest)(nil),
		(*ShellRequest_Data)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[4].OneofWrappers = []any{
		(*ShellResponse_Data)(nil),
		(*ShellResponse_Terminate)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[8].OneofWrappers = []any{
		(*PortForwardRequest_Destination)(nil),
		(*PortForwardRequest_Data)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[11].OneofWrappers = []any{
		(*ExecRequest_CommandDetails)(nil),
		(*ExecRequest_Input)(nil),
		(*ExecRequest_Signal)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[12].OneofWrappers = []any{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
		(*ExecResponse_ExitCode)(nil),
	}
	file_pkg_api_k8shelld_proto_msgTypes[14].OneofWrappers = []any{
		(*UnixSocketRequest_StartRequest)(nil),
		(*UnixSocketRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_k8shelld_proto_rawDesc), len(file_pkg_api_k8shelld_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_pkg_api_k8shelld_proto_goTypes,
		DependencyIndexes: file_pkg_api_k8shelld_proto_depIdxs,
		EnumInfos:         file_pkg_api_k8shelld_proto_enumTypes,
		MessageInfos:      file_pkg_api_k8shelld_proto_msgTypes,
	}.Build()
	File_pkg_api_k8shelld_proto = out.File
	file_pkg_api_k8shelld_proto_goTypes = nil
	file_pkg_api_k8shelld_proto_depIdxs = nil
}
